server:
  port: 8081

spring:
  application:
    name: stock-provider
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        passwork: nacos
        namespace: public

