server:
  port: 8082

spring:
  application:
    name: order-provider
  cloud:
    nacos:
        server-addr: 127.0.0.1:8848
        discovery:
          namespace: public
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nacos_config?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: admin